name: CI Build

env:
  RELEASE_DIR: artifacts
  GITCLIFF_VER: 2.11.0

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:
  cross_build:
    runs-on: ${{ matrix.os }}
    container:
      image:  ${{ matrix.image }}
    strategy:
      matrix:
        include:
          - os: docker
            target: x86_64-unknown-linux-musl
            image: "rust:latest"
            profile: release
            use_cross: false
            run_tests: true
            tool: cargo
            exe: jsavlt

    steps:
      - name: Install Node.js
        run: |
          apt-get update
          apt-get install -y nodejs

      - name: Install Cross
        if: matrix.use_cross
        run: cargo install cross

      - name: Install Cross-Compilation Tools
        run: |
          apt-get update
          apt-get install -y gcc-aarch64-linux-gnu musl-tools
          ln -s /usr/bin/aarch64-linux-gnu-gcc /usr/bin/aarch64-linux-musl-gcc

      - uses: actions/checkout@v4

      - name: Build
        run: |
          rustup target add ${{ matrix.target }}
          ${{ matrix.tool }} build --target="${{ matrix.target }}" --profile "${{ matrix.profile }}" --workspace
        env:
          CROSS_CONTAINER_IN_CONTAINER: true

      - name: Test
        if: matrix.run_tests
        run: |
          cargo test --target="${{ matrix.target }}" --profile "${{ matrix.profile }}" --workspace

  generate-changelog:
    name: Generate changelog
    if: startsWith(forgejo.ref, 'refs/tags/v')
    runs-on: docker
    outputs:
      release_body: ${{ steps.changelog.outputs.release_body }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install git-cliff
        run: |
          curl -fL \
            https://github.com/orhun/git-cliff/releases/download/v${{ env.GITCLIFF_VER }}/git-cliff-${{ env.GITCLIFF_VER }}-x86_64-unknown-linux-musl.tar.gz \
            | tar -xz
          install git-cliff-${{ env.GITCLIFF_VER }}/git-cliff /usr/local/bin/git-cliff

      - name: Generate a changelog
        id: changelog
        run: |
          BODY="$(git cliff --latest --strip header)"
          echo "release_body<<EOF" >> "$GITHUB_OUTPUT"
          echo "$BODY" >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"