name: CI Build

env:
  GITCLIFF_VER: 2.11.0
  PROFILE: release
  RELEASE_BIN: rlox

on:
  push:
    branches:
      - master
  pull_request:
    branches: [ master ]

jobs:
  cross_build:
    runs-on: docker
    container:
      image:  registry.egoroff.spb.ru/rustcross:1.93
    strategy:
      matrix:
        include:
          - target: aarch64-apple-darwin
            run_tests: false
            osx: true
            windows: false
            exe: rlox
          - target: x86_64-apple-darwin
            run_tests: false
            osx: true
            windows: false
            exe: rlox
          - target: x86_64-unknown-linux-musl
            run_tests: true
            osx: false
            windows: false
            exe: rlox
          - target: aarch64-unknown-linux-musl
            run_tests: false
            osx: false
            windows: false
            exe: rlox
          - target: x86_64-pc-windows-msvc
            run_tests: false
            osx: false
            windows: true
            exe: rlox.exe
          - target: aarch64-pc-windows-msvc
            run_tests: false
            osx: false
            windows: true
            exe: rlox.exe

    steps:
      - name: Query version number
        id: get_version
        shell: bash
        run: |
          echo "using version tag ${GITHUB_REF:11}"
          echo "version=${GITHUB_REF:11}" >> $GITHUB_OUTPUT

      # -------------------
      # Checkout the repository after Node.js is installed
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.READ_PEPOS_TOKEN }}

      # -------------------
      # Set macOS environment variables for SDK
      - name: Set macOS build env
        if: matrix.osx
        run: |
          echo RUSTFLAGS=-Lframework=/opt/MacOSX11.3.sdk/System/Library/Frameworks >> $GITHUB_ENV
          echo MACOSX_DEPLOYMENT_TARGET=10.12 >> $GITHUB_ENV
          echo SDKROOT=/opt/MacOSX11.3.sdk >> $GITHUB_ENV

      # -------------------
      # Build Linux or Mac
      - name: Build Linux or Mac
        if: ${{ !matrix.windows }}
        run: |
          env
          cargo zigbuild --target="${{ matrix.target }}" --profile "${{ env.PROFILE }}"

      # -------------------
      # Build Windows
      - name: Build Windows
        if: matrix.windows
        run: |
          cargo xwin build --target="${{ matrix.target }}" --profile "${{ env.PROFILE }}"

      # -------------------
      # Run tests
      - name: Tests
        if: matrix.run_tests
        run: |
          cargo zigbuild --target="${{ matrix.target }}" --profile "${{ env.PROFILE }}" --workspace --tests
          find target/${{ matrix.target }}/${{ env.PROFILE }}/deps/ -regex '^[^.]*$' -type f -executable -exec {} \;

      # -------------------
      # Package the build artifacts
      - name: Packaging
        id: packaging
        run: |
          artefact=${{ env.RELEASE_BIN }}-${{ steps.get_version.outputs.VERSION }}-${{ matrix.target }}.tar.gz
          target_dir=./target/${{ matrix.target }}/${{ env.PROFILE }}/
          (cd "$target_dir" && tar czvf "$artefact" "${{ matrix.exe }}")
          echo "artefact=$artefact" >> $GITHUB_OUTPUT

      # -------------------
      # Upload artifacts
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: ./target/${{ matrix.target }}/${{ env.PROFILE }}/${{ steps.packaging.outputs.artefact }}
