[package]
name = "interpreter"
version = "0.1.0"
edition = "2024"

[dependencies]
scanner = { path = "../scanner" }
miette = { workspace = true, features = ["fancy"] }
thiserror = "2.0.12"

[dev-dependencies]
test-case = "3.3.1"
